### ISSUE TITLE
Hello author, there should be no problem with my path, but the following error occurred

### ISSUE THREAD

**Issue by Halleyawoo** [cchen-cc/SIFA#21]
2020-11-02 21:30:08.748194: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-11-02 21:30:08.845787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:1a:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-11-02 21:30:08.845820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:1a:00.0, compute capability: 6.1)
2020-11-02 21:30:13.247364: W tensorflow/core/kernels/queue_base.cc:303] _2_input_producer_3: Skipping cancelled dequeue attempt with queue not closed
Traceback (most recent call last):
  File "/media/nomachine/project/SIFA-master/main.py", line 559, in <module>
    main(config_filename='/media/nomachine/project/SIFA-master/config_param.json')
  File "/media/nomachine/project/SIFA-master/main.py", line 554, in main
    sifa_model.train()
  File "/media/nomachine/project/SIFA-master/main.py", line 358, in train
    images_i, images_j, gts_i, gts_j = sess.run(self.inputs)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_7_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Caused by op u'shuffle_batch', defined at:
  File "/media/nomachine/project/SIFA-master/main.py", line 559, in <module>
    main(config_filename='/media/nomachine/project/SIFA-master/config_param.json')
  File "/media/nomachine/project/SIFA-master/main.py", line 554, in main
    sifa_model.train()
  File "/media/nomachine/project/SIFA-master/main.py", line 311, in train
    self.inputs = data_loader.load_data(self._source_train_pth, self._target_train_pth, True)
  File "/media/nomachine/project/SIFA-master/data_loader.py", line 84, in load_data
    images_i, images_j, gt_i, gt_j = tf.train.shuffle_batch([image_i, image_j, gt_i, gt_j], BATCH_SIZE, 500, 100)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 1225, in shuffle_batch
    name=name)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 796, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 464, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2418, in _queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/hfcui/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): RandomShuffleQueue '_7_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

**Comment by cchen-cc** [comment]
This type of error usually happens when data cannot be correctly read.
There can be various causes for why data are not read correctly and usually careful debugging is needed.
Usually you could check the following things:
- whether the data paths stored in imagea_list and imageb_list are correct
- whether the data written into the tfrecords are with correct shape and type
- whether the data reading in the data_load.py is with correct shape and type
