### ISSUE TITLE
numpy, medpy version

### ISSUE THREAD

**Issue by Neronjust2017** [cchen-cc/SIFA#48]
Hi, thanks for your work! When I run evaluate.py, the following problem happens: 
```
Traceback (most recent call last):
  File "/home/weiyuhua/Medical_Image_Segmentation/SIFA/evaluate.py", line 239, in <module>
    main(config_filename='./config_param.json')
  File "/home/weiyuhua/Medical_Image_Segmentation/SIFA/evaluate.py", line 235, in main
    sifa_model.test()
  File "/home/weiyuhua/Medical_Image_Segmentation/SIFA/evaluate.py", line 202, in test
    assd_list.append(mmb.assd(pred_test_data_tr, pred_gt_data_tr))
  File "/home/weiyuhua/Medical_Image_Segmentation/envs/py27/local/lib/python2.7/site-packages/medpy/metric/binary.py", line 404, in assd
    assd = numpy.mean( (asd(result, reference, voxelspacing, connectivity), asd(reference, result, voxelspacing, connectivity)) )
  File "/home/weiyuhua/Medical_Image_Segmentation/envs/py27/local/lib/python2.7/site-packages/medpy/metric/binary.py", line 512, in asd
    sds = __surface_distances(result, reference, voxelspacing, connectivity)
  File "/home/weiyuhua/Medical_Image_Segmentation/envs/py27/local/lib/python2.7/site-packages/medpy/metric/binary.py", line 1169, in __surface_distances
    result_border = result - binary_erosion(result, structure=footprint, iterations=1)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

```
It seems that the version of numpy(1.14) is incompatible with the medpy(0.3). I tried to downgrade numpy, but tensorflow(1.10.0) requires numpy version >= 1.13, which also leads to the same problem. So which numpy and medpy versions do you use in your environment?

**Comment by cchen-cc** [comment]
If I remembered it correctly, I modified the code in medpy that causes this problem, as the TypeError indicated how to fix it.

**Comment by Neronjust2017** [comment]
@cchen-cc Ok, thanks!
